# Generated by Django 4.0 on 2024-02-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=15, verbose_name='соперник'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=15, verbose_name='игрок'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stage_end_date',
            field=models.DateField(verbose_name='дата окончания игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stage_number',
            field=models.PositiveIntegerField(verbose_name='счет'),
        ),
    ]
