# Generated by Django 4.0 on 2024-02-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_game_description_alter_game_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(verbose_name='описание игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=15, verbose_name='название игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stage_end_date',
            field=models.DateField(verbose_name='дата окончания этапа'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stage_number',
            field=models.PositiveIntegerField(verbose_name='номер этапа'),
        ),
    ]
